#!/bin/bash

# 判断参数个数
if [ $# -lt 1 ]
then
    echo "Usage: xsu <username>"
    exit;
fi

# 遍历集群所有机器
for host in hadoop102 hadoop103 hadoop104
do
    echo ==================== $host ====================
    # 切换到指定用户并执行 bash，保持交互
    ssh $host "su - $1"
done
