#!/bin/bash

# 1. 判断参数个数
if [ $# -lt 1 ]
then
  echo "Not Enough Arguement!"
  exit;
fi

# 2. 遍历集群所有机器（根据你的主机名修改，通常是 hadoop102, hadoop103, hadoop104）
for host in hadoop102 hadoop103 hadoop104
do
    echo ==================== $host ====================
    # 3. 遍历所有目录，挨个发送
    # $* 代表所有参数（即你要发送的文件路径）
    for file in $@
    do
        # 4. 判断文件是否存在
        if [ -e $file ]
            then
                # 5. 获取父目录
                pdir=$(cd -P $(dirname $file); pwd)
                # 6. 获取当前文件的名称
                fname=$(basename $file)
                # 7. 使用 ssh 在远程机器创建目录，并使用 rsync 同步文件
                ssh $host "mkdir -p $pdir"
                rsync -av $pdir/$fname $host:$pdir
            else
                echo $file does not exists!
        fi
    done
done
